#!/bin/sh

if [ -e /run/systemd/container ]; then
    exit 0
fi

echo "Read RTC to sys..." > /tmp/rtc_my_log.log
if [ -e /dev/rtc ]; then
	hwclock --rtc=/dev/rtc --hctosys
	echo "Read RTC done!" >> /tmp/rtc_my_log.log
else
	echo "Read RTC failed!" >> /tmp/rtc_my_log.log
fi
